// <auto-generated />
namespace ShareHolderMeeting.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _201604260449113_addFilesTable3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201604260449113_addFilesTable3));
        
        string IMigrationMetadata.Id
        {
            get { return "201604260643298_201604260449113_addFilesTable3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
