// <auto-generated />
namespace ShareHolderMeeting.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addAmtAlreadyVoted_VotingCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAmtAlreadyVoted_VotingCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201603020427526_addAmtAlreadyVoted_VotingCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
